### ISSUE TITLE
exec binary does not work on Java 9+

### ISSUE THREAD

**Issue by totakke** [chrovis/cljam#133]
```console
$ lein bin
...
Creating standalone executable: /path/to/cljam/target/cljam

# 1.8
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ target/cljam version
0.5.2-SNAPSHOT

# 9
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
$ target/cljam version
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)

# 10
$ java -version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
$ target/cljam -h
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        ... (same error)

**Comment by alumi** [comment]
FWIW, I couldn't reproduce the bug in CI and my local env (macOS 10.13.5, Java 9.0.1 & 1.8.0_131) 🤔

https://github.com/chrovis/cljam/compare/fix/upgrade-deps#diff-354f30a63fb0907d4ad57269548329e3R25

```diff
diff --git .travis.yml .travis.yml
index 00148b5..104dc56 100644
--- .travis.yml
+++ .travis.yml
@@ -4,16 +4,25 @@ cache:
   directories:
     - $HOME/.m2
 jdk:
+  - oraclejdk10
   - oraclejdk9
   - oraclejdk8
+  - openjdk11
+  - openjdk10
+  - openjdk9
   - openjdk8
-  - openjdk7
 env:
   matrix:
-    - VERSION='1.7'
     - VERSION='1.8'
     - VERSION='1.9'
-script: lein with-profile dev,$VERSION test
+    - VERSION='1.10'
+before_install:
+  - if [ -f "${JAVA_HOME}/lib/security/cacerts" -a -w  "${JAVA_HOME}/lib/security/cacerts" ]; then rm "${JAVA_HOME}/lib/security/cacerts" && ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi;
+script:
+    - lein with-profile dev,$VERSION test
+    - lein bin
+    - java -version
+    - target/cljam version
 jobs:
   include:
     - stage: coverage
```

https://travis-ci.org/chrovis/cljam/builds/395312419

**Comment by totakke** [comment]
On my environment (`master` branch), Clojure version also seems to affect this problem.

- Clojure 1.8 (`lein bin`) + Java 1.8 -> work 😄 
- Clojure 1.8 (`lein bin`) + Java 9+ -> error 😖 
- Clojure 1.7 (`lein with-profile +1.7 bin`) + Java 1.8 -> work 😄 
- Clojure 1.7 (`lein with-profile +1.7 bin`) + Java 9+ -> error 😖 
- Clojure 1.9 (`lein with-profile +1.9 bin`) + Java 1.8 -> work 😄 
- Clojure 1.9 (`lein with-profile +1.9 bin`) + Java 9+ -> work 😄

but these patterns are tested the above CI config. umm...

**Comment by alumi** [comment]
Oops! I forgot to specify Clojure verisons in the CI... 😵 

`lein bin` => `lein with-profile dev,$VERSION bin`

It's now failing on Clojure 1.8 with Java 9+
https://travis-ci.org/chrovis/cljam/builds/395327461

**Comment by alumi** [comment]
Maybe this is related to [CLJ-2077](https://dev.clojure.org/jira/browse/CLJ-2077)

```clojure
(defmacro ^:private when-class [class-name & body]
  `(try
     (Class/forName ^String ~class-name)
     ~@body
     (catch ClassNotFoundException _#)))

(when-class "java.sql.Timestamp"
  (load "instant"))
```

**Comment by totakke** [comment]
That may be right. Leiningen <2.8 also had the same problem.

```clojure
:uberjar {:dependencies [[org.clojure/clojure "1.9.0"]
```

just resolves this issue.

**Comment by alumi** [comment]
or we can use Clojure 1.8 with Java 9+ by setting `--add-modules` option and unset the bootclasspath

```diff
diff --git project.clj project.clj
index 7cfd6a1..e734624 100644
--- project.clj
+++ project.clj
@@ -30,7 +30,11 @@
                    :main ^:skip-aot cljam.tools.main
                    :global-vars {*warn-on-reflection* true}}
              :1.7 {:dependencies [[org.clojure/clojure "1.7.0"]]}
-             :1.8 {:dependencies [[org.clojure/clojure "1.8.0"]]}
+             :1.8 {:dependencies [[org.clojure/clojure "1.8.0"]]
+                   :bin {:jvm-opts ~(if (<= 9 (Integer/parseInt (re-find #"^\d+" (System/getProperty "java.version"))))
+                                      ["--add-modules" "java.sql"]
+                                      [])
+                         :bootclasspath ~(> 9 (Integer/parseInt (re-find #"^\d+" (System/getProperty "java.version"))))}}
              :1.9 {:dependencies [[org.clojure/clojure "1.9.0"]]}
              :1.10 {:dependencies [[org.clojure/clojure "1.10.0-alpha4"]]}
              :uberjar {:dependencies [[org.clojure/clojure "1.9.0"]
```

**Comment by totakke** [comment]
Yes, but that is more than necessary. It is simple and enough to create working binary with clojure 1.9.

**Comment by alumi** [comment]
I agree 😃
I opened PR #134 using Clojure 1.9.
Thanks.

**Comment by totakke** [comment]
@alumi Thanks!
